language: go

go:
  - 1.6
  - 1.7
  - tip

install:
    - go get -v github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
    - glide install

notifications:
    email:
        - korenaga.makoto@gmail.com